services:
  counterdistill:
    build:
      context: ..
      dockerfile: docker/Dockerfile

    image: counterdistill:local

    working_dir: /app

    volumes:
      - ../data:/app/data
      - ../database:/app/database
      - ../outputs:/app/outputs
      - ../mlruns:/app/mlruns

    environment:
      PYTHONUNBUFFERED: "1"

    command:
      - python
      - -m
      - src.modeling.train
      - model=random_forest

    profiles:
      - tools


  mlflow:
    build:
      context: ..
      dockerfile: docker/Dockerfile

    image: counterdistill:local

    working_dir: /app

    ports:
      - "5000:5000"

    volumes:
      - ../database:/app/database
      - ../mlruns:/app/mlruns

    command:
      - mlflow
      - server
      - --backend-store-uri
      - sqlite:///database/mlflow.db
      - --host
      - 0.0.0.0
      - --port
      - "5000"
      - --workers
      - "1"

    restart: unless-stopped


  dashboard:
    build:
      context: ..
      dockerfile: docker/Dockerfile

    image: counterdistill:local

    working_dir: /app

    ports:
      - "8501:8501"

    volumes:
      - ../database:/app/database

    environment:
      PYTHONUNBUFFERED: "1"

    command:
      - streamlit
      - run
      - app/app.py
      - --server.address=0.0.0.0
      - --server.port=8501

    restart: unless-stopped
